### ISSUE TITLE
Output escaped with rails3 + haml

### ISSUE THREAD

**Issue by timuckun** [jamesarosen/xebec#2]
When I call  = nav_bar in haml the output is escaped. If I call !=nav_bar the output is still escaped.

The only way to get this to work in rails3 is to call CGI.escapeHTML(nav_bar.to_s).

**Comment by jamesarosen** [comment]
Thanks for reporting this. I think I've fixed the issue in 2.6.1. Please let me know. Resolved in 21ddbb7e6c5413685846aa53b6d25ffb762a2e0c.

**Comment by timuckun** [comment]
It works as expected now. Thanks.
